// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Session A Session is a browser based session object that stores the currently authenticate user principal
//
//
// swagger:model Session
type Session struct {

	// The client that created the user session
	ClientID string `json:"client_id,omitempty"`

	// The token creation time
	CreatedAt int64 `json:"created_at,omitempty"`

	// The token expiration time
	ExpiresAt int64 `json:"expires_at,omitempty"`

	// The session id
	ID string `json:"id,omitempty"`

	// Subject is the user subject id
	Subject string `json:"subject,omitempty"`
}

// Validate validates this session
func (m *Session) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Session) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Session) UnmarshalBinary(b []byte) error {
	var res Session
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
