package auth

// ----------------------------------------------------------------------------
// Code generated by `swagger generate operation`. DO NOT EDIT.
//
// See scripts/generate-swagger-api.sh
// ----------------------------------------------------------------------------
