// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
)

// NewUserInfoGetParams creates a new UserInfoGetParams object
// no default values defined in spec.
func NewUserInfoGetParams() UserInfoGetParams {

	return UserInfoGetParams{}
}

// UserInfoGetParams contains all the bound params for the user info get operation
// typically these are obtained from a http.Request
//
// swagger:parameters UserInfoGet
type UserInfoGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUserInfoGetParams() beforehand.
func (o *UserInfoGetParams) BindRequest(r *http.Request) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
