// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/libatomic/oauth/pkg/oauth"
)

// NewUserInfoUpdateParams creates a new UserInfoUpdateParams object
// no default values defined in spec.
func NewUserInfoUpdateParams() UserInfoUpdateParams {

	return UserInfoUpdateParams{}
}

// UserInfoUpdateParams contains all the bound params for the user info update operation
// typically these are obtained from a http.Request
//
// swagger:parameters UserInfoUpdate
type UserInfoUpdateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The new profile
	  In: body
	*/
	Profile *oauth.Profile
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUserInfoUpdateParams() beforehand.
func (o *UserInfoUpdateParams) BindRequest(r *http.Request, c ...runtime.Consumer) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) && len(c) > 0 {
		route := middleware.MatchedRoute{
			Consumer: c[0],
		}
		route.Formats = strfmt.NewFormats()
		defer r.Body.Close()
		var body oauth.Profile
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("profile", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Profile = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
