// Code generated by go-swagger; DO NOT EDIT.

package oauth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"database/sql/driver"
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Session A Session is a browser based session object that stores the currently authenticate user principal
//
//
// swagger:model Session
type Session struct {

	// The client that created the user session
	ClientID string `json:"client_id,omitempty"`

	// The token creation time
	CreatedAt int64 `json:"created_at,omitempty"`

	// The token expiration time
	ExpiresAt int64 `json:"expires_at,omitempty"`

	// The session id
	ID string `json:"id,omitempty"`

	// Subject is the user subject id
	Subject string `json:"subject,omitempty"`
}

// Validate validates this session
func (m *Session) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Session) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Session) UnmarshalBinary(b []byte) error {
	var res Session
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// Value returns Session as a value that can be stored as json in the database
func (m Session) Value() (driver.Value, error) {
	return json.Marshal(m)
}

// Scan reads a json value from the database into a Session
func (m *Session) Scan(value interface{}) error {
	b, ok := value.([]byte)
	if !ok {
		return errors.New(http.StatusInternalServerError, "type assertion to []byte failed")
	}

	if err := json.Unmarshal(b, &m); err != nil {
		return err
	}

	return nil
}
